name: Update JSON Data & README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5'
  push:
    branches:
      - main
    paths:
      - 'config/config.yml'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Update JSON data
        run: python run.py update

      - name: Build updated README
        run: python run.py build

      - name: Commit and push changes
        run: |-
          git add .
          git diff
          git config --global user.email "github-action-bot@specterops.io"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated JSON & README with the updated config" -a || echo "No changes to commit"
          git push
